version: '3.8'

services:
 server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env.dev
    volumes:
      - ./src:/app/src
      - /app/node_modules
      - /app/.pnpm_store

 postgres:
    image: postgres:latest
    container_name: pg_postgres
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
 postgres_data:
