version: '3.8'

services:
 server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - postgres_db
    env_file:
      - .env.dev
    volumes:
      - ./src:/app/src
      # - ./node_modules:/app/node_modules
      # - /app/.pnpm_store

 postgres_db:
    image: postgres:latest
    container_name: pg_postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=multi-tenant-rbac
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
 postgres_data:
